import type { Metadata } from "next";
import Link from "next/link";
import "./architecture.css";

export const metadata: Metadata = {
  title: "Zero Trust Architecture — Arduwyn",
  description:
    "Reference architecture, identity chain, SASE stack, compliance mapping, and migration playbook for enterprise Zero Trust. Built for healthcare, financial services, and cloud enterprises.",
};

const LEGACY_POINTS = [
  "Trust is location-based: inside the network = trusted",
  "VPN extends the corporate LAN to every endpoint",
  "TLS 1.3 / QUIC / ECDHE silently break inspection",
  "Lateral movement is unconstrained once inside",
  "Third-party access is granted at the network layer",
  "Compliance evidence depends on perimeter integrity",
  "Post-merger network unification takes 2–4 years",
];

const ZT_POINTS = [
  "Trust is per-request: identity + device + context",
  "No network-level access; users connect to apps, not networks",
  "Encrypted-traffic visibility through architectural design, not point tools",
  "Lateral movement constrained by microsegmentation by default",
  "Third-party access scoped to a single app, time-boxed",
  "Compliance evidence is generated by the control plane",
  "Post-merger unification is a policy operation, not a network rebuild",
];

const REF_STACK = [
  {
    title: "Identity",
    desc: "The new perimeter. Single source of truth for users, devices, and workloads with continuous posture evaluation.",
    tech: ["Entra ID", "Okta", "Ping", "Conditional Access"],
  },
  {
    title: "Edge / SASE",
    desc: "Inline traffic control with TLS inspection, DLP, CASB, and threat prevention applied at the cloud edge — not at the branch firewall.",
    tech: ["Zscaler ZIA", "ZDX", "Inline DLP", "CASB"],
  },
  {
    title: "Workforce Access",
    desc: "ZTNA replacing VPN. Users connect to specific applications, not subnets. Third-party and contractor access is scoped per app per session.",
    tech: ["Zscaler ZPA", "App Connectors", "Browser Access"],
  },
  {
    title: "Workload & Cloud",
    desc: "AWS and Azure native controls layered with microsegmentation and posture management. Workload identity, not network identity, is the access principle.",
    tech: ["AWS Security Hub", "Defender for Cloud", "Microsegmentation"],
  },
  {
    title: "Endpoint",
    desc: "EDR and posture feed back into the access plane so device health is part of every authorization decision.",
    tech: ["CrowdStrike Falcon", "Defender for Endpoint", "Posture API"],
  },
  {
    title: "AI Guardrails",
    desc: "Inline visibility and control for ChatGPT, Copilot, and agent-mode tooling. Prompt-level DLP and exfiltration prevention for the workflows traditional controls don't see.",
    tech: ["Inline GenAI DLP", "Agent-mode guardrails", "Prompt visibility"],
  },
];

const IDENTITY_CHAIN = [
  { n: "01", t: "User", d: "Verified identity from the IdP" },
  { n: "02", t: "Device", d: "Health + posture from EDR" },
  { n: "03", t: "Context", d: "Location, time, risk score" },
  { n: "04", t: "Policy", d: "Conditional access evaluation" },
  { n: "05", t: "App", d: "Scoped to one application" },
  { n: "06", t: "Audit", d: "Decision logged for compliance" },
];

const COMPLIANCE = [
  {
    label: "Healthcare",
    fw: "HIPAA",
    p: "Security Rule alignment via identity-centric access, audit trail generation, and PHI-aware inline DLP.",
  },
  {
    label: "Financial",
    fw: "PCI DSS 4.0",
    p: "Segmentation and scoping reductions, MFA enforcement, and continuous monitoring across the CDE.",
  },
  {
    label: "Federal / Best practice",
    fw: "NIST CSF 2.0",
    p: "Core functions mapped to architecture controls, with Zero Trust Maturity Model alignment scoring.",
  },
  {
    label: "Privacy",
    fw: "GDPR",
    p: "Data residency, processing visibility, and right-to-erasure workflows supported by the access plane.",
  },
];

const PHASES = [
  {
    num: "01",
    meta: "Days 1–30",
    h: "Assess & baseline",
    p: "Identity, network, and workload inventory. Current-state architecture diagram. Zero Trust Maturity Model scoring. Compliance gap mapping per framework. Output: a target-state architecture and a sequenced execution plan.",
  },
  {
    num: "02",
    meta: "Months 1–3",
    h: "Identity foundation",
    p: "Consolidate to a single IdP, harden conditional access, deploy MFA at the right strength for each user class, integrate device posture from EDR. Everything that follows depends on this layer being solid.",
  },
  {
    num: "03",
    meta: "Months 3–6",
    h: "Edge & workforce access",
    p: "ZIA inline for internet traffic with TLS inspection, DLP, and CASB. ZPA for private apps replacing the VPN. App Connectors deployed close to workloads, not in a central data center.",
  },
  {
    num: "04",
    meta: "Months 6–12",
    h: "Workload, cloud, microsegmentation",
    p: "Native controls in AWS and Azure layered with microsegmentation. Workload identity wired into the access plane. AI guardrails for GenAI and agent-mode tooling. Third-party access scoped per app.",
  },
  {
    num: "05",
    meta: "Months 12–18",
    h: "Decommission legacy",
    p: "Retire VPN concentrators, flatten legacy firewall complexity, retire the access controls that no longer serve a purpose. Continuous attestation of the new posture for the next audit cycle.",
  },
];

export default function ArchitecturePage() {
  return (
    <>
      <section className="page-hero">
        <div className="container">
          <span className="hero-eyebrow">Reference Architecture</span>
          <h1>
            <span className="accent-i">Zero Trust</span> Architecture
          </h1>
          <p>
            Identity-centric, perimeter-eliminated, encryption-aware. The architecture we
            deploy in production at enterprise scale — and the migration path to get there
            from where you actually are today.
          </p>
        </div>
      </section>

      <section className="container">
        <div className="section-head">
          <h2>The architecture problem</h2>
          <p>
            Legacy network security was built for an estate that no longer exists. Zero
            Trust starts from the assumption it&apos;s already breached.
          </p>
        </div>
        <div className="compare">
          <div className="col legacy">
            <h3>Legacy / Perimeter</h3>
            <ul>
              {LEGACY_POINTS.map((p) => (
                <li key={p}>{p}</li>
              ))}
            </ul>
          </div>
          <div className="col zt">
            <h3>Zero Trust</h3>
            <ul>
              {ZT_POINTS.map((p) => (
                <li key={p}>{p}</li>
              ))}
            </ul>
          </div>
        </div>
      </section>

      <section className="container">
        <div className="section-head">
          <h2>Reference architecture</h2>
          <p>The layered stack we deploy. Vendor-agnostic in pattern, opinionated in execution.</p>
        </div>
        <div className="ref-stack">
          {REF_STACK.map(({ title, desc, tech }) => (
            <div className="ref-row" key={title}>
              <h4>{title}</h4>
              <div className="desc">
                {desc}
                <div>
                  {tech.map((t) => (
                    <span className="tech" key={t}>
                      {t}
                    </span>
                  ))}
                </div>
              </div>
            </div>
          ))}
        </div>
      </section>

      <section className="container">
        <div className="section-head">
          <h2>The identity chain</h2>
          <p>
            Every access decision evaluates this chain. If any link fails, the decision
            fails — not just the connection.
          </p>
        </div>
        <div className="chain">
          {IDENTITY_CHAIN.map(({ n, t, d }) => (
            <div className="step" key={n}>
              <div className="n">{n}</div>
              <div className="t">{t}</div>
              <div className="d">{d}</div>
            </div>
          ))}
        </div>
      </section>

      <section className="container">
        <div className="section-head">
          <h2>Compliance mapping</h2>
          <p>
            The frameworks the architecture is designed against from day one — not
            retrofitted at audit time.
          </p>
        </div>
        <div className="compliance">
          {COMPLIANCE.map(({ label, fw, p }) => (
            <div className="c" key={fw}>
              <div className="label">{label}</div>
              <div className="fw">{fw}</div>
              <p>{p}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="container">
        <div className="section-head">
          <h2>Migration path</h2>
          <p>Five phases. Phase 1 starts producing security value within 30 days.</p>
        </div>
        <div className="phases">
          {PHASES.map(({ num, meta, h, p }) => (
            <div className="phase" key={num}>
              <div className="num">{num}</div>
              <div>
                <span className="meta">{meta}</span>
                <h4>{h}</h4>
                <p>{p}</p>
              </div>
            </div>
          ))}
        </div>
      </section>

      <section id="contact" className="container">
        <div className="cta-band">
          <span className="eyebrow">Engage</span>
          <h2>Want this architecture for your environment?</h2>
          <p>
            Tell us about the current state, the constraint, and the deadline. We respond
            within one business day.
          </p>
          <div className="btn-row">
            <a
              className="btn btn-primary"
              href="mailto:hello@arduwyn.com?subject=Architecture%20Engagement"
            >
              hello@arduwyn.com
            </a>
            <Link className="btn btn-ghost" href="/engineering">
              See engineering depth
            </Link>
          </div>
        </div>
      </section>
    </>
  );
}
