/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL path (auto-lowercased), e.g. "home" or "architecture".
   */
  slug: string;
  /**
   * Compose the page from reusable blocks.
   */
  layout?:
    | (
        | {
            eyebrow?: string | null;
            heading: string;
            subheading?: string | null;
            buttons?:
              | {
                  label: string;
                  href: string;
                  style?: ('primary' | 'ghost') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            eyebrow?: string | null;
            /**
             * Wrap accent words in *asterisks*, e.g. Industry *Focus*.
             */
            heading: string;
            subheading?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pageHero';
          }
        | {
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            eyebrow?: string | null;
            /**
             * Optional. *accent* supported.
             */
            heading?: string | null;
            subheading?: string | null;
            /**
             * Paragraphs separated by a blank line. *accent* supported.
             */
            body: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'lede';
          }
        | {
            eyebrow?: string | null;
            /**
             * *accent* supported.
             */
            heading?: string | null;
            subheading?: string | null;
            items?:
              | {
                  icon?: ('none' | 'finance' | 'healthcare') | null;
                  /**
                   * *accent* supported.
                   */
                  title: string;
                  lede?: string | null;
                  bullets?:
                    | {
                        text: string;
                        muted?: boolean | null;
                        id?: string | null;
                      }[]
                    | null;
                  linkLabel?: string | null;
                  href?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'industryTiles';
          }
        | {
            eyebrow?: string | null;
            /**
             * *accent* supported.
             */
            heading?: string | null;
            subheading?: string | null;
            items?:
              | {
                  tag?: string | null;
                  title: string;
                  body?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'callouts';
          }
        | {
            eyebrow?: string | null;
            /**
             * *accent* supported.
             */
            heading?: string | null;
            subheading?: string | null;
            intro?: string | null;
            tags?:
              | {
                  label: string;
                  placeholder?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Optional dashed placeholder note shown below the tags.
             */
            note?: {
              tag?: string | null;
              body?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'platformTags';
          }
        | {
            eyebrow?: string | null;
            /**
             * *accent* supported.
             */
            heading?: string | null;
            subheading?: string | null;
            tag?: string | null;
            body: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'placeholder';
          }
        | {
            eyebrow?: string | null;
            /**
             * *accent* supported.
             */
            heading?: string | null;
            subheading?: string | null;
            panelStyle?: ('boxed' | 'bare') | null;
            steps?:
              | {
                  /**
                   * e.g. 01. Blank = auto-number.
                   */
                  number?: string | null;
                  /**
                   * Optional small kicker (e.g. a date).
                   */
                  meta?: string | null;
                  /**
                   * *accent* supported.
                   */
                  title: string;
                  body?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'numberedTimeline';
          }
        | {
            eyebrow?: string | null;
            /**
             * *accent* supported.
             */
            heading?: string | null;
            subheading?: string | null;
            columns?: ('2' | '3' | '4') | null;
            items?:
              | {
                  /**
                   * Icon key (see components/Icon.tsx). Optional.
                   */
                  icon?: string | null;
                  /**
                   * Serif number shown instead of an icon. Optional.
                   */
                  number?: string | null;
                  tag?: string | null;
                  /**
                   * *accent* supported (wrap the whole title to make it italic-accent).
                   */
                  title: string;
                  body?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featureCards';
          }
        | {
            /**
             * *accent* supported.
             */
            body: string;
            button?: {
              label?: string | null;
              href?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'calloutBar';
          }
        | {
            eyebrow?: string | null;
            /**
             * *accent* supported.
             */
            heading?: string | null;
            subheading?: string | null;
            columns?: ('2' | '3' | '4') | null;
            items?:
              | {
                  /**
                   * Optional small label above the term.
                   */
                  kicker?: string | null;
                  term: string;
                  body?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'statGrid';
          }
        | {
            eyebrow?: string | null;
            /**
             * *accent* supported.
             */
            heading?: string | null;
            subheading?: string | null;
            items?:
              | {
                  /**
                   * Short badge, e.g. ZIA.
                   */
                  code?: string | null;
                  /**
                   * *accent* supported.
                   */
                  title: string;
                  lede?: string | null;
                  bullets?:
                    | {
                        text: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'productCards';
          }
        | {
            /**
             * *accent* supported.
             */
            heading: string;
            /**
             * Big accent number, e.g. 27.
             */
            count?: string | null;
            intro?: string | null;
            columns?: ('2' | '3') | null;
            items?:
              | {
                  /**
                   * Blank = auto-number.
                   */
                  number?: string | null;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'numberedGrid';
          }
        | {
            eyebrow?: string | null;
            /**
             * *accent* supported.
             */
            heading?: string | null;
            subheading?: string | null;
            layout?: ('grid' | 'stack') | null;
            items?:
              | {
                  /**
                   * *accent* supported.
                   */
                  title: string;
                  description?: string | null;
                  tags?:
                    | {
                        label: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'labeledRows';
          }
        | {
            eyebrow?: string | null;
            /**
             * *accent* supported.
             */
            heading?: string | null;
            subheading?: string | null;
            columns?: ('2' | '3') | null;
            groups?:
              | {
                  label?: string | null;
                  tags?:
                    | {
                        label: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'tagGroups';
          }
        | {
            /**
             * Title-bar caption.
             */
            label?: string | null;
            lines?:
              | {
                  text?: string | null;
                  style?: ('command' | 'output' | 'success') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'terminal';
          }
        | {
            eyebrow?: string | null;
            /**
             * *accent* supported.
             */
            heading?: string | null;
            subheading?: string | null;
            stages?:
              | {
                  number?: string | null;
                  /**
                   * *accent* supported.
                   */
                  title: string;
                  blurb?: string | null;
                  columns?: ('1' | '2') | null;
                  tools?:
                    | {
                        /**
                         * Monospace path label.
                         */
                        modPath?: string | null;
                        title: string;
                        lede?: string | null;
                        bullets?:
                          | {
                              /**
                               * Inline `code` supported.
                               */
                              text: string;
                              id?: string | null;
                            }[]
                          | null;
                        tags?:
                          | {
                              label: string;
                              id?: string | null;
                            }[]
                          | null;
                        wide?: boolean | null;
                        guardTitle?: string | null;
                        guardBullets?:
                          | {
                              /**
                               * Inline `code` supported.
                               */
                              text: string;
                              id?: string | null;
                            }[]
                          | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'toolStages';
          }
        | {
            eyebrow?: string | null;
            /**
             * *accent* supported.
             */
            heading: string;
            sub?: string | null;
            ctas?:
              | {
                  label: string;
                  href: string;
                  style?: ('primary' | 'ghost') | null;
                  id?: string | null;
                }[]
              | null;
            showDiagram?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'homeHero';
          }
        | {
            /**
             * Optional HTML id for in-page links (e.g. "about").
             */
            anchor?: string | null;
            eyebrow?: string | null;
            /**
             * *accent* supported.
             */
            heading?: string | null;
            subheading?: string | null;
            /**
             * Paragraphs separated by a blank line. *accent* supported.
             */
            story?: string | null;
            groups?:
              | {
                  label?: string | null;
                  tags?:
                    | {
                        label: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            focusLabel?: string | null;
            focus?: string | null;
            ctaLabel?: string | null;
            ctaHref?: string | null;
            differentiators?:
              | {
                  /**
                   * Icon key (see components/Icon.tsx).
                   */
                  icon?: string | null;
                  title: string;
                  body?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'aboutSplit';
          }
        | {
            eyebrow?: string | null;
            /**
             * *accent* supported.
             */
            heading?: string | null;
            subheading?: string | null;
            items?:
              | {
                  /**
                   * Icon key (see components/Icon.tsx).
                   */
                  icon?: string | null;
                  /**
                   * *accent* supported.
                   */
                  title: string;
                  body?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'outcomes';
          }
        | {
            /**
             * Optional HTML id for in-page links (e.g. "services").
             */
            anchor?: string | null;
            eyebrow?: string | null;
            /**
             * *accent* supported.
             */
            heading?: string | null;
            subheading?: string | null;
            items?:
              | {
                  tag?: string | null;
                  /**
                   * *accent* supported.
                   */
                  title: string;
                  bullets?:
                    | {
                        text: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'serviceCards';
          }
        | {
            /**
             * Optional HTML id for in-page links (e.g. "portfolio").
             */
            anchor?: string | null;
            /**
             * *accent* supported.
             */
            heading?: string | null;
            subheading?: string | null;
            ctaLabel?: string | null;
            ctaHref?: string | null;
            items?:
              | {
                  /**
                   * Optional. Upload images first in the Media collection, then pick one here. ~16:10 ratio looks best (e.g. 1200×750). If left blank, the card falls back to a placeholder icon.
                   */
                  image?: (number | null) | Media;
                  /**
                   * Optional small kicker.
                   */
                  vertical?: string | null;
                  /**
                   * *accent* supported.
                   */
                  title: string;
                  /**
                   * Short blurb shown on the card.
                   */
                  summary?: string | null;
                  ctaLabel?: string | null;
                  /**
                   * Modal opening line (shown right under the title in the modal).
                   */
                  lede?: string | null;
                  /**
                   * Up to 3 highlight stats shown in a row inside the modal.
                   */
                  stats?:
                    | {
                        /**
                         * e.g. "120K+", "VPN-free", "2+ yrs"
                         */
                        value: string;
                        /**
                         * Small caption under the value.
                         */
                        label: string;
                        id?: string | null;
                      }[]
                    | null;
                  /**
                   * Modal: the SITUATION paragraph.
                   */
                  situation?: string | null;
                  /**
                   * Modal: the APPROACH bullet list.
                   */
                  approach?:
                    | {
                        text: string;
                        id?: string | null;
                      }[]
                    | null;
                  /**
                   * Modal: the OUTCOME paragraph.
                   */
                  outcome?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'caseStudies';
          }
        | {
            eyebrow?: string | null;
            /**
             * *accent* supported.
             */
            heading?: string | null;
            subheading?: string | null;
            items?:
              | {
                  tag?: string | null;
                  /**
                   * *accent* supported.
                   */
                  title: string;
                  summary?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'briefCards';
          }
        | {
            eyebrow?: string | null;
            /**
             * *accent* supported.
             */
            heading?: string | null;
            subheading?: string | null;
            items?:
              | {
                  tag?: string | null;
                  /**
                   * *accent* supported.
                   */
                  title: string;
                  forText?: string | null;
                  receiveLabel?: string | null;
                  receive?: string | null;
                  duration?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Centered note below the lanes. *accent* supported.
             */
            note?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'laneCards';
          }
        | {
            heading?: string | null;
            items?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            eyebrow?: string | null;
            /**
             * *accent* supported.
             */
            heading: string;
            body?: string | null;
            buttons?:
              | {
                  label: string;
                  href: string;
                  style?: ('primary' | 'ghost') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              subheading?: T;
              buttons?:
                | T
                | {
                    label?: T;
                    href?: T;
                    style?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        pageHero?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              subheading?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        lede?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              subheading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        industryTiles?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              subheading?: T;
              items?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    lede?: T;
                    bullets?:
                      | T
                      | {
                          text?: T;
                          muted?: T;
                          id?: T;
                        };
                    linkLabel?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        callouts?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              subheading?: T;
              items?:
                | T
                | {
                    tag?: T;
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        platformTags?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              subheading?: T;
              intro?: T;
              tags?:
                | T
                | {
                    label?: T;
                    placeholder?: T;
                    id?: T;
                  };
              note?:
                | T
                | {
                    tag?: T;
                    body?: T;
                  };
              id?: T;
              blockName?: T;
            };
        placeholder?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              subheading?: T;
              tag?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        numberedTimeline?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              subheading?: T;
              panelStyle?: T;
              steps?:
                | T
                | {
                    number?: T;
                    meta?: T;
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        featureCards?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              subheading?: T;
              columns?: T;
              items?:
                | T
                | {
                    icon?: T;
                    number?: T;
                    tag?: T;
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        calloutBar?:
          | T
          | {
              body?: T;
              button?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              id?: T;
              blockName?: T;
            };
        statGrid?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              subheading?: T;
              columns?: T;
              items?:
                | T
                | {
                    kicker?: T;
                    term?: T;
                    body?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        productCards?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              subheading?: T;
              items?:
                | T
                | {
                    code?: T;
                    title?: T;
                    lede?: T;
                    bullets?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        numberedGrid?:
          | T
          | {
              heading?: T;
              count?: T;
              intro?: T;
              columns?: T;
              items?:
                | T
                | {
                    number?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        labeledRows?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              subheading?: T;
              layout?: T;
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    tags?:
                      | T
                      | {
                          label?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        tagGroups?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              subheading?: T;
              columns?: T;
              groups?:
                | T
                | {
                    label?: T;
                    tags?:
                      | T
                      | {
                          label?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        terminal?:
          | T
          | {
              label?: T;
              lines?:
                | T
                | {
                    text?: T;
                    style?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        toolStages?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              subheading?: T;
              stages?:
                | T
                | {
                    number?: T;
                    title?: T;
                    blurb?: T;
                    columns?: T;
                    tools?:
                      | T
                      | {
                          modPath?: T;
                          title?: T;
                          lede?: T;
                          bullets?:
                            | T
                            | {
                                text?: T;
                                id?: T;
                              };
                          tags?:
                            | T
                            | {
                                label?: T;
                                id?: T;
                              };
                          wide?: T;
                          guardTitle?: T;
                          guardBullets?:
                            | T
                            | {
                                text?: T;
                                id?: T;
                              };
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        homeHero?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              sub?: T;
              ctas?:
                | T
                | {
                    label?: T;
                    href?: T;
                    style?: T;
                    id?: T;
                  };
              showDiagram?: T;
              id?: T;
              blockName?: T;
            };
        aboutSplit?:
          | T
          | {
              anchor?: T;
              eyebrow?: T;
              heading?: T;
              subheading?: T;
              story?: T;
              groups?:
                | T
                | {
                    label?: T;
                    tags?:
                      | T
                      | {
                          label?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              focusLabel?: T;
              focus?: T;
              ctaLabel?: T;
              ctaHref?: T;
              differentiators?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        outcomes?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              subheading?: T;
              items?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        serviceCards?:
          | T
          | {
              anchor?: T;
              eyebrow?: T;
              heading?: T;
              subheading?: T;
              items?:
                | T
                | {
                    tag?: T;
                    title?: T;
                    bullets?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        caseStudies?:
          | T
          | {
              anchor?: T;
              heading?: T;
              subheading?: T;
              ctaLabel?: T;
              ctaHref?: T;
              items?:
                | T
                | {
                    image?: T;
                    vertical?: T;
                    title?: T;
                    summary?: T;
                    ctaLabel?: T;
                    lede?: T;
                    stats?:
                      | T
                      | {
                          value?: T;
                          label?: T;
                          id?: T;
                        };
                    situation?: T;
                    approach?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    outcome?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        briefCards?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              subheading?: T;
              items?:
                | T
                | {
                    tag?: T;
                    title?: T;
                    summary?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        laneCards?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              subheading?: T;
              items?:
                | T
                | {
                    tag?: T;
                    title?: T;
                    forText?: T;
                    receiveLabel?: T;
                    receive?: T;
                    duration?: T;
                    id?: T;
                  };
              note?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              buttons?:
                | T
                | {
                    label?: T;
                    href?: T;
                    style?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}